analytics: {}
color:
  brandColors:
    - '#B0B0A8'
    - '#000000'
    - '#A8A8A0'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0.615625
  saturation: 0.5
cta: {}
layout_spectrum: 1
name: Cuisine
opengraph: {}
purpose: []
typography_spectrum: 0.43066
