color:
  brandColors:
    - '#C8C8A0'
    - '#586028'
    - '#889060'
    - '#E04030'
    - '#E86850'
  brandStrength: 0.5
  lightness: 0
  rhythmicContrast: 0.615625
  saturation: 0.5
layout_spectrum: 0.796875
name: Cuisine
typography_spectrum: 0.098437
