name: Cuisine
favicon: null
layout_spectrum: 0.8418687931261957
typography_spectrum: 0.26347039081156254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.6978592467494309
  lightness: 0.38226709980517626
  saturation: 0.3971970865968615
  rhythmicContrast: 0.3737804463598877
purpose: []
