name: Cuisine
favicon: null
layout_spectrum: 0.020694490522146225
typography_spectrum: 0.10171548696234822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.8508225444238633
  lightness: 0.2365098271984607
  saturation: 0.2564459501300007
  rhythmicContrast: 0.6640161504037678
purpose: []
