analytics: {}
color:
  brandColors:
    - '#B8BDC3'
    - '#9E6A42'
    - '#665E30'
    - '#87919A'
    - '#584622'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: Cuisine
opengraph: {}
purpose: []
typography_spectrum: 0.43066
