analytics: {}
color:
  brandColors:
    - '#EDC096'
    - '#FAF4F6'
    - '#C58754'
    - '#1B0400'
    - '#5C2A0F'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 1
name: Cuisine
opengraph: {}
purpose: []
typography_spectrum: 0.43066
