name: Cuisine
favicon: null
layout_spectrum: 0.08353616506792605
typography_spectrum: 0.016969304997473955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.9519350782502443
  lightness: 0.3893613340333104
  saturation: 0.3960208192002028
  rhythmicContrast: 0.191817234037444
purpose: []
