analytics: {}
color:
  brandColors:
    - '#B0B0A8'
    - '#000000'
    - '#A8A8A0'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.506578
  saturation: 1
cta: {}
layout_spectrum: 1
name: Cuisine
opengraph: {}
purpose: []
typography_spectrum: 0.43066
