name: Cuisine
favicon: null
layout_spectrum: 0.796875
typography_spectrum: 0.43066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8C8A0'
    - '#586028'
    - '#889060'
    - '#E04030'
    - '#E86850'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.615625
purpose: []
